# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/AuraHealthDB
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8086

# JWT
jwt.secret=QXVyYUhlYWx0aFNlY3JldEtleUZvckpXVDIwMjRTZWN1cmUhISE=